-- ========================================================================
-- ZENHR SAAS - MASTER SUPABASE SCHEMA (PostgreSQL)
-- Updated for Supabase Auth Compatibility (UUID)
-- ========================================================================

-- 1. Subscription Plans
CREATE TABLE IF NOT EXISTS subscription_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name TEXT NOT NULL,
    max_employees INT DEFAULT 10,
    price DECIMAL(10, 2) DEFAULT 0.00,
    is_active BOOLEAN DEFAULT TRUE,
    features TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Companies Table (Multi-tenant Core)
CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    company_logo TEXT,
    admin_name TEXT,
    admin_email TEXT UNIQUE NOT NULL,
    admin_password TEXT NOT NULL,
    status TEXT DEFAULT 'ACTIVE', 
    plan_id BIGINT REFERENCES subscription_plans(id),
    employee_count INT DEFAULT 0,
    address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Role Master
CREATE TABLE IF NOT EXISTS role_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name TEXT NOT NULL, -- owner, superAdmin, admin, hr, manager, employee
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Users / Employees Table (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY, -- Linked directly to auth.users.id
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    employee_code TEXT UNIQUE,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT, -- Not used for login (Supabase Auth handles it)
    phone TEXT,
    role_id BIGINT REFERENCES role_master(id),
    is_active BOOLEAN DEFAULT TRUE,
    profile_pic TEXT,
    join_date DATE DEFAULT CURRENT_DATE,
    designation TEXT,
    department TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Attendance Table
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE, -- Match UUID
    log_date DATE DEFAULT CURRENT_DATE,
    clock_in TIMESTAMPTZ,
    clock_out TIMESTAMPTZ,
    status TEXT, -- Present, Late, Half-Day
    total_hours DECIMAL(5, 2),
    location TEXT
);

-- 6. Leave Types
CREATE TABLE IF NOT EXISTS leave_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    leave_name TEXT NOT NULL, 
    leave_count DECIMAL(5, 2) NOT NULL,
    financial_year TEXT NOT NULL DEFAULT '2024-2025',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Leave Requests
CREATE TABLE IF NOT EXISTS leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES users(id) ON DELETE CASCADE, -- Match UUID
    leave_type_id BIGINT REFERENCES leave_types(id),
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    total_days DECIMAL(5, 2) NOT NULL,
    session_type TEXT DEFAULT 'FULL_DAY', -- FULL_DAY, FIRST_HALF, SECOND_HALF
    reason TEXT,
    financial_year TEXT NOT NULL DEFAULT '2024-2025',
    status TEXT DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    reject_reason TEXT,
    approver_id UUID REFERENCES users(id), -- Match UUID
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Biometric Machines Table
CREATE TABLE IF NOT EXISTS biometric_machines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    device_name TEXT NOT NULL,
    ip_address TEXT NOT NULL,
    serial_number TEXT NOT NULL,
    status TEXT DEFAULT 'Online',
    last_sync TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Projects Table
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    project_name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Sub-Projects Table
CREATE TABLE IF NOT EXISTS sub_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
    sub_project_name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);

-- ========================================================================
-- SEED DATA (Initial Values)
-- ========================================================================

-- Insert Plans
INSERT INTO subscription_plans (plan_name, max_employees, price) VALUES 
('Free Trial', 5, 0.00),
('Basic', 20, 19.99),
('Enterprise', 999, 99.99);

-- Insert Roles (Exactly as used in AppConstants)
INSERT INTO role_master (role_name) VALUES 
('owner'), ('superAdmin'), ('admin'), ('hr'), ('manager'), ('employee');
